version: '3.4'

services:
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #DATABASE_URL: "sqlserver://sa:Sa123456@goDB?database=goDB"
      #SERVER_URL: "sqlserver://sa:Sa123456@goDB/" 
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - "ConnectionStrings:DbConnection=Server=msSqlDb;Database=Messaging;User Id=sa;Password=Sa123456"
    ports:
      - "8000:80"
    restart: unless-stopped
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
    links: 
      - msSqlDb # This service depends on redis. Start that first.
     
    #volumes:
    #  - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
  msSqlDb:
    container_name: msSqlDb
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    restart: unless-stopped
    environment:
      SA_PASSWORD: "Sa123456"
      ACCEPT_EULA: "Y"
    volumes:
      - ./sqlserver-data1:/var/lib/sqlserver/data
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

# Networks to be created to facilitate communication between containers
networks:
  backend:
    driver: "bridge"